# Custom updater for external tools using custom GitHub Action
name: External Dependencies Check
on:
  schedule:
    - cron: '0 0 * * MON'  # Run weekly on Monday
  workflow_dispatch:  # Allow manual triggers

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check latest versions
        id: versions
        run: |
          # Function to get latest release version
          get_latest_version() {
            curl -s "https://api.github.com/repos/$1/releases/latest" | jq -r .tag_name | sed 's/^v//'
          }

          # Function to get latest Docker image tag
          get_docker_tag() {
            curl -s "https://hub.docker.com/v2/repositories/$1/tags?page_size=100" | \
            jq -r '.results[].name' | grep -v 'edge' | grep -v 'latest' | sort -V | tail -n1
          }

          # Check versions
          KUBECTL_VERSION=$(get_latest_version "kubernetes/kubernetes")
          HELM_VERSION=$(get_latest_version "helm/helm")
          HELM_SECRETS_VERSION=$(get_latest_version "jkroepke/helm-secrets")
          SOPS_VERSION=$(get_latest_version "mozilla/sops")
          AWS_CLI_VERSION=$(get_latest_version "aws/aws-cli")
          HELMFILE_VERSION=$(get_latest_version "helmfile/helmfile")
          HELM_S3_VERSION=$(get_latest_version "hypnoglow/helm-s3")
          HELM_DIFF_VERSION=$(get_latest_version "databus23/helm-diff")
          ALPINE_VERSION=$(get_docker_tag "library/alpine")
          PYTHON_VERSION=$(get_docker_tag "library/python")

          # Create or update .env file with new versions
          cat > .env.new << EOF
          KUBERNETES_VERSIONS=["${KUBECTL_VERSION}"]
          HELM_VERSION=${HELM_VERSION}
          AWS_CLI_VERSION=${AWS_CLI_VERSION}
          SOPS_VERSION=${SOPS_VERSION}
          HELM_SECRETS_VERSION=${HELM_SECRETS_VERSION}
          HELM_S3_VERSION=${HELM_S3_VERSION}
          HELMFILE_VERSION=${HELMFILE_VERSION}
          HELM_DIFF_VERSION=${HELM_DIFF_VERSION}
          ALPINE_VERSION=${ALPINE_VERSION}
          PYTHON_VERSION=${PYTHON_VERSION}
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update external dependencies"
          title: "chore(deps): update external dependencies"
          body: |
            Updates external dependencies to their latest versions:
            
            - Alpine: ${{ steps.versions.outputs.ALPINE_VERSION }}
            - Python: ${{ steps.versions.outputs.PYTHON_VERSION }}
            - Kubectl: ${{ steps.versions.outputs.KUBECTL_VERSION }}
            - Helm: ${{ steps.versions.outputs.HELM_VERSION }}
            - Helm Secrets: ${{ steps.versions.outputs.HELM_SECRETS_VERSION }}
            - SOPS: ${{ steps.versions.outputs.SOPS_VERSION }}
            - AWS CLI: ${{ steps.versions.outputs.AWS_CLI_VERSION }}
            - Helmfile: ${{ steps.versions.outputs.HELMFILE_VERSION }}
            - Helm S3: ${{ steps.versions.outputs.HELM_S3_VERSION }}
            - Helm Diff: ${{ steps.versions.outputs.HELM_DIFF_VERSION }}
          branch: "deps/external-updates"
          delete-branch: true
          labels: |
            dependencies
            automated pr
